project_id = "hvfelpmrlexkntkgotpt"

[functions.stripe-webhook]
verify_jwt = false

[functions.daily-spin-reward]
verify_jwt = true

[functions.translate-content]
verify_jwt = false

[functions.setup-admin-users]
verify_jwt = false
